services:
  tdengine:
    image : tdengine/tdengine:3.3.6.0
    container_name: tdengine
    hostname: tdengine
    # linux/amd64 or linux/arm64, depends on your platform
    platform: linux/amd64
    environment:
      TAOS_FQDN: "tdengine"
      MONITOR_FQDN: "tdengine"
      EXPLORER_CLUSTER: "http://tdengine:6041"
      TAOS_KEEPER_TDENGINE_HOST: "tdengine"
      TZ: Asia/Shanghai
    volumes:
      - tdengine-data:/var/lib/taos/
    ports:
      - 6060:6060
  tdgpt:
    image: tdengine/tdengine-tdgpt:3.3.6.0
    container_name: tdgpt
    # linux/amd64 or linux/arm64, depends on your platform
    platform: linux/amd64
    environment:
      TZ: Asia/Shanghai
    ports:
      - 6090:6090
  grafana:
    image: grafana/grafana:11.0.11
    container_name: grafana
    volumes:
      - ./tdengine.yml:/etc/grafana/provisioning/datasources/tdengine.yml
      - grafana-data:/var/lib/grafana
    environment:
      # install tdengine plugin at start
      GF_INSTALL_PLUGINS: "tdengine-datasource"
      TDENGINE_API: "http://tdengine:6041"
      TDENGINE_BASIC_AUTH: "cm9vdDp0YW9zZGF0YQ=="
      TZ: Asia/Shanghai
    ports:
      - 3000:3000
volumes:
  grafana-data:
  tdengine-data:
