version: "3.7"

services:
  tdengine:
    image: image.cloud.taosdata.com/tdengine/tdengine-preview:3.3.6.0-arm64
    #image : tdengine/tdengine-aarch64:3.3.5.8 
    container_name: tdengine
    hostname: tdengine
    environment:
      TAOS_FQDN: "tdengine"
      MONITOR_FQDN: "tdengine"
      EXPLORER_CLUSTER: "http://tdengine:6041"
      TAOS_KEEPER_TDENGINE_HOST: "tdengine"
    volumes:
      - tdengine-data:/var/lib/taos/
    ports:
      - 6060:6060
  tdgpt:
    image: image.cloud.taosdata.com/tdgpt/tdgpt-aarch64:3.3.6.0
    container_name: tdgpt
    ports:
      - 6090:6090
  grafana:
    image: grafana/grafana:11.0.11
    container_name: grafana
    volumes:
      - ./tdengine.yml:/etc/grafana/provisioning/datasources/tdengine.yml
      - grafana-data:/var/lib/grafana
    environment:
      # install tdengine plugin at start
      GF_INSTALL_PLUGINS: "tdengine-datasource"
      TDENGINE_API: "http://tdengine:6041"
      TDENGINE_BASIC_AUTH: "cm9vdDp0YW9zZGF0YQ=="
    ports:
      - 3000:3000
volumes:
  grafana-data:
  tdengine-data:
